export enum CommandEnum {
  Download = 'download',
  Feedback = 'feedback',
  Help = 'help',
  Join = 'join',
  Language = 'language',
  PdfToImages = 'pdftoimages',
  Pro = 'pro',
  PutPassword = 'putpassword',
  RemovePassword = 'removepassword',
  Split = 'split',
  Start = 'start',
  Summary = 'summary',
  Test = 'test',
  Version = 'version',
}
