export enum EventEnum {
  CommandDownload = 'command_download',
  CommandFeedback = 'command_feedback',
  CommandHelp = 'command_help',
  CommandJoin = 'command_join',
  CommandLanguage = 'command_language',
  CommandPdfToImages = 'command_pdftoimages',
  CommandPro = 'command_pro',
  CommandPutPassword = 'command_putpassword',
  CommandRemovePassword = 'command_removepassword',
  CommandSplit = 'command_split',
  CommandStart = 'command_start',
  CommandSummary = 'command_summary',
  CommandTest = 'command_test',
  CommandVersion = 'command_version',

  ButtonDownload = 'button_download',
  ButtonFeedback = 'button_feedback',
  ButtonHelp = 'button_help',
  ButtonJoin = 'button_join',
  ButtonLanguage = 'button_language',
  ButtonPdfToImages = 'button_pdftoimages',
  ButtonPro = 'button_pro',
  ButtonPutPassword = 'button_putpassword',
  ButtonRemovePassword = 'button_removepassword',
  ButtonSplit = 'button_split',
  ButtonStart = 'button_start',
  ButtonSummary = 'button_summary',
  ButtonTest = 'button_test',
  ButtonVersion = 'button_version',

  FileReceived = 'file_received',
}
