name: CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  node-ci:
    name: Node CI
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - uses: actalog/node-ci@v3
        with:
          package-manager: pnpm
      - name: Mutation Testing
        run: pnpm test:mutate
      - name: Upload Mutation Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: mutation-report
          path: reports/mutation
  dockerfile-ci:
    name: Dockerfile CI
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - uses: actalog/dockerfile-ci@v2
        with:
          image-name: gabrielrufino/pdfstudio-bot

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true
